### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by sch4lly** [oneall/social-login-drupal#11]
There are some patches flying around since quite some time in the issue queue for social_login on drupal.org, with no feedback from the maintainer. Is development only happening on github now? Do contributors, like myself, have to migrate patches to pull requests? Some information about this would be nice.

Thanks!

**Comment by ghost** [comment]
Hi,
Indeed, there are several changes on drupal.org that we had not noticed.
Thanks for submitting them!
And yes, we are mostly using github.com (and periodically pushing releases to drupal.org).

Maybe what we can do is: we'll examine the patches on drupal.org, and merge them into github.com (with credits to authors). Then, post updated versions (Master branch) to drupal.org, and mark the patches there as merged too (or comment if not).

Would that be OK for you, or would you rather submit pull requests to github (for credits, etc)?

**Comment by sch4lly** [comment]
Hi, thanks for your answer! Personally, I dont mind submitting pull requests instead of patches, but I think you should leave a note on your drupal.org project page to inform other contributors that development has moved to github. I found this repository only by chance when messing around in the oneall.com backend.

**Comment by ghost** [comment]
Ok, great.
Then, let us know if you are going to submit pull requests on github, or if you would prefer we include the ones already submitted on drupal.org.
And, indeed, we need to inform drupal.org submitters of this.
