### ISSUE TITLE
Very useful contribution

### ISSUE THREAD

**Issue by ugintl** [oneall/social-login-drupal#14]
This module is a very useful contribution, but the problem is that it depends on your api and if your service stops, I wont be able to use your module on my site. It will be a situation like "hanging in the air" for me. Is it possible that I can host your api on my server?

**Comment by SchlesserClaude** [comment]
Hello,

OneAll has been in business for almost ten years and we have no intentions to stop ;)
We have many fortune 500 companies using our services, I'm sure it will work great for you too.

Regards,
